"use client";

import React from "react";
import { ApiError, getJobCandidates, listJobs, updateRecruiterState } from "@/lib/api/client";
import type { JobCandidateScreeningResponse, JobResponse } from "@/lib/api/types";
import { getStoredJobId, storeJobId } from "@/lib/resume-session";
import { Button } from "@/components/ui/button";

export default function ShortlistsPage() {
  const [jobs, setJobs] = React.useState<JobResponse[]>([]); const [jobId, setJobId] = React.useState(""); const [rows, setRows] = React.useState<JobCandidateScreeningResponse[]>([]); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null);
  React.useEffect(() => { const load = async () => { try { const items = await listJobs(); setJobs(items); const saved = getStoredJobId(); const selected = saved && items.some((item) => item.id === saved) ? saved : items[0]?.id ?? ""; setJobId(selected); } catch (value) { setError(value instanceof ApiError ? value.message : "Could not load jobs."); } finally { setLoading(false); } }; void load(); }, []);
  React.useEffect(() => { if (!jobId) { setRows([]); return; } const load = async () => { setLoading(true); setError(null); try { const result = await getJobCandidates(jobId); setRows(result.candidates.filter((item) => item.shortlisted)); storeJobId(jobId); } catch (value) { setRows([]); setError(value instanceof ApiError ? value.message : "Could not load shortlisted candidates."); } finally { setLoading(false); } }; void load(); }, [jobId]);
  const remove = async (row: JobCandidateScreeningResponse) => { try { const state = await updateRecruiterState(row.screening_result_id, { shortlisted: false }); setRows((items) => items.filter((item) => item.candidate_id !== row.candidate_id || state.shortlisted)); } catch (value) { setError(value instanceof ApiError ? value.message : "Could not update shortlist state."); } };
  const selected = jobs.find((job) => job.id === jobId);
  return <div className="space-y-6 pb-12"><div className="flex flex-col gap-4 border-b border-zinc-200 pb-5 md:flex-row md:items-center md:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight text-zinc-950">Shortlists</h1><p className="mt-1 text-sm text-zinc-500">Persisted recruiter shortlist state; automated screening evidence is not changed here.</p></div><label className="text-xs font-semibold text-zinc-700">Target job<select className="ml-2 h-9 rounded-md border border-zinc-200 bg-white px-2 text-xs" value={jobId} onChange={(event) => setJobId(event.target.value)}><option value="">Select a persisted job</option>{jobs.map((job) => <option key={job.id} value={job.id}>{job.title} — {job.company_name}</option>)}</select></label></div>{selected && <div className="rounded-lg border border-zinc-200 bg-zinc-50 p-3 text-xs text-zinc-600"><span className="font-semibold text-zinc-900">{selected.title}</span> · {selected.company_name || "Not provided"} · {selected.requirements.length} backend requirements</div>}{error && <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}{loading ? <div className="rounded-lg border border-zinc-200 bg-white p-12 text-center text-sm text-zinc-500">Loading persisted shortlist...</div> : !jobId ? <div className="rounded-lg border border-zinc-200 bg-white p-12 text-center text-sm text-zinc-500">Create a job and run a screening to use recruiter shortlists.</div> : rows.length === 0 ? <div className="rounded-lg border border-zinc-200 bg-white p-12 text-center text-sm text-zinc-500">No candidates are shortlisted for this job.</div> : <div className="overflow-hidden rounded-lg border border-zinc-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-zinc-50 text-xs text-zinc-500"><tr><th className="p-3">Candidate</th><th className="p-3">Automated score</th><th className="p-3">Recruiter stage</th><th className="p-3" /></tr></thead><tbody>{rows.map((row) => <tr key={row.candidate_id} className="border-t border-zinc-100"><td className="p-3 font-medium text-zinc-900">{row.candidate_name}</td><td className="p-3">{row.overall_score === null ? "Unavailable" : `${row.overall_score}%`}</td><td className="p-3">{row.recruiter_stage}</td><td className="p-3 text-right"><Button size="sm" variant="outline" onClick={() => void remove(row)}>Remove</Button></td></tr>)}</tbody></table></div>}</div>;
}
