import type { EvaluationReportResponse } from "@/lib/api/types";
import type { CandidateEvaluationReport } from "@/types/report";

const colors = ["#2563eb", "#16a34a", "#d97706", "#7c3aed"];

export function presentEvaluationReport(report: EvaluationReportResponse, context?: { candidateName?: string | null; jobTitle?: string | null; companyName?: string | null; documentName?: string | null }): CandidateEvaluationReport {
  const alignment = [...report.required_alignment, ...report.preferred_alignment];
  const strengths = alignment.filter((item) => item.status === "matched").map((item) => item.requirement);
  const verification = alignment.filter((item) => item.evidence_status === "needs_verification" || item.status === "partially_supported").map((item) => item.requirement);
  const gaps = [...report.skill_gap_summary.required_gaps, ...report.skill_gap_summary.preferred_gaps];
  const languages = report.github_context.signals.filter((signal) => signal.signal_type === "github_language");
  const repositories = report.github_context.signals.filter((signal) => signal.signal_type === "github_repository");
  return {
    header: { reportId: report.screening_result_id, reportDate: new Date(report.generated_at).toLocaleString(), evaluationStatus: report.final_assessment.classification, candidateName: context?.candidateName || "Not provided", targetRole: context?.jobTitle || "Not provided", targetCompany: context?.companyName || "Not provided", documentName: context?.documentName || "Selected resume" },
    executiveSummary: { overallCompatibility: `${report.overall_score.toFixed(1)}%`, compatibilityLevel: report.final_assessment.classification === "strong_fit" ? "Strong" : report.final_assessment.classification === "low_fit" ? "Developing" : "Moderate", strongestAreas: strengths, areasNeedingVerification: verification, majorSkillGaps: gaps, verdictSummary: `${report.final_assessment.explanation} Reason codes: ${report.final_assessment.reason_codes.join(", ") || "none"}.` },
    resumeProfile: { technicalFocus: "Derived from stored screening evidence.", education: [], experience: [], certifications: [] },
    skillsEvidence: alignment.map((item) => ({ name: item.requirement, category: item.importance, status: item.evidence_status === "strong_evidence" ? "Strong evidence" : item.evidence_status === "supported" ? "Supported" : item.evidence_status === "weak_evidence" ? "Weak evidence" : item.evidence_status === "needs_verification" ? "Needs verification" : "Not found", strength: item.status === "matched" ? "High" : item.status === "partially_supported" ? "Unverified" : "Low", sources: { skillsSection: item.evidence_snippets.length > 0, project: false, experience: false, certification: false, github: false }, keyProof: item.evidence_snippets.join(" ") || item.reason })),
    jobAlignment: alignment.map((item) => ({ requirement: item.requirement, priority: item.importance === "required" ? "Must have" : "Preferred", candidateCapability: item.evidence_status ?? "No supported skill", status: item.status === "matched" ? "Matched" : item.status === "partially_supported" ? "Needs verification" : "Missing", supportingEvidence: item.evidence_snippets.join(" ") || item.reason, gapCallout: item.status === "unsupported" ? item.reason : undefined })),
    skillGaps: gaps.map((skill) => { const resource = report.learning_recommendations.find((item) => item.skill === skill); return { skill, tier: "Missing", status: "Gap", reason: resource?.reason ?? "No stored resume evidence satisfies this requirement.", recommendation: resource ? `${resource.resource_title}: ${resource.learning_path.join(", ")}` : "No curated recommendation available." }; }),
    developerIntelligence: { languageDistribution: languages.map((signal, index) => ({ name: signal.label, percentage: Number(signal.details.repository_count ?? 0), color: colors[index % colors.length], linesOfCode: "Not provided by GitHub snapshot", primaryFocus: "Public repository language" })), keyProjects: repositories.map((signal) => ({ id: signal.id, name: signal.label, description: String(signal.details.description ?? "Public repository"), architectureScope: "Not provided", technologies: [String(signal.details.language ?? "Unspecified")], repoUrl: signal.source_url ?? "", relevance: "Public evidence", evidenceBadge: "Public GitHub" })), codingProfiles: [], commitSummary: report.github_context.available ? `Public GitHub context for ${report.github_context.username ?? "candidate"}; fetched ${report.github_context.fetched_at ?? "unknown"}.` : "No cached public GitHub context is available." },
    evidenceNote: `Automated status: ${report.automated_status}. Semantic summary: ${report.semantic_matching.note} Persisted semantic evidence: ${report.semantic_matching.persisted_semantic_evidence_count}. Recruiter state is shown separately and does not alter automated evidence.`,
    finalAssessment: { strengths, concerns: gaps, verificationRecommendations: verification, developmentRecommendations: report.learning_recommendations.map((item) => `${item.skill}: ${item.resource_title} — ${item.learning_path.join(", ")}`), hiringDecisionAdvice: `${report.final_assessment.classification}: ${report.final_assessment.explanation}` },
  };
}
